spring.application.name=Journal-App
spring.data.mongodb.uri=mongodb+srv://piyushlodhi40_db_user:bo7IsqTmsFOdy1HD@cluster0.cn8xhio.mongodb.net/?appName=Cluster0
spring.data.mongodb.database=journaldb
spring.data.mongodb.auto-index-creation=true